import { LightColors } from "../themes/colors.slint";

export component IconButton {
    in property <image> icon;
    in property <length> size: 36px;
    in property <length> icon-size: 20px;
    in property <bool> enabled: true;

    callback clicked();

    width: size;
    height: size;

    states [
        hover when touch-area.has-hover && enabled: {
            background.background: LightColors.button-hover;
        }
        pressed when touch-area.pressed && enabled: {
            background.background: LightColors.button-active;
        }
    ]

    background := Rectangle {
        width: 100%;
        height: 100%;
        border-radius: parent.width / 2;
        background: transparent;

        animate background { duration: 100ms; }
    }

    Image {
        source: icon;
        width: icon-size;
        height: icon-size;
        colorize: enabled ? LightColors.text-secondary : #CCCCCC;
    }

    touch-area := TouchArea {
        clicked => {
            if (enabled) {
                root.clicked();
            }
        }
    }
}
